### ISSUE TITLE
Support for Cypress

### ISSUE THREAD

**Issue by azaeng04** [hirezio/given#5]
**Is your feature request related to a problem? Please describe.**
I would like to be able to make use of the Given, When, Then structure in Cypress tests to keep consistency.

**Describe the solution you'd like**
Given, When and Then the same way it is implemented on Jest/Jasmine tests

**Describe alternatives you've considered**
Cucumber

**Comment by shairez** [comment]
Thanks @azaeng04 !

Although Cucumber and GWT originally was written for E2E acceptance tests), this library was built to be used in "unit tests" to make them focused on being more "single action" focused and not "multi-action" (like E2E tests).

A newer alternative by the way is the library [single](https://github.com/hirezio/single) (and hence the name :)

To add support for Cypress is  to create a whole different library (something like https://github.com/TheBrainFamily/cypress-cucumber-preprocessor)

I suggest using the `context()` function in cypress alongside the `describe` and `it` to create more separation, but still keep it  multi-action tests because E2E tests are expensive to run so I wouldn't be adding a bunch of those "single action" tests
