### ISSUE TITLE
[Question] Will this library still be maintained?

### ISSUE THREAD

**Issue by azaeng199104** [hirezio/given#7]
Just noticed that there hasn't been any publishes since last year.
Considering whether to use this library or not.

**Comment by shairez** [comment]
This is a small library that doesn't require a lot of maintenance, because it's pretty much feature complete.

But if you want even a better structure check out my newer library -

https://github.com/hirezio/single

I rewrote all of observer-spy and auto-spies to use this as I believe this will be the future test structure for single-action tests

And I'm going to maintain them both for sure, so don't worry about abandonment :)

**Comment by azaeng199104** [comment]
Thanks @shairez ! :D
